App Estacionamento/Controllers/TicketController.cs
using App_Estacionamento.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;
using App_Estacionamento.Services;
using Microsoft.AspNetCore.Authorization;
using Gerencianet.NETCore.SDK;
using System.Diagnostics;
using Newtonsoft.Json.Linq;
using System.Drawing;
using System;
using System.IO;
#nullable disable

namespace App_Estacionamento.Controllers
{
    //[Authorize]
    public class TicketController : Controller
    {
        // URL da api Rodrigo
        const string urlApi = "https://localhost:7210/api/Ticket/";
        const string urlApiPagamento = "https://localhost:7210/api/Pagamento/";
        // URL da api Carlos
        //const string urlApi = "https://localhost:5007/api/Ticket/";
        // ObterTodos
        // ObterTodosNaoPagos
        // ObterId/{id}
        // Incluir
        // Alterar/{id}
        // Excluir/{id}

        /// <summary>
        /// Página de Controle de Tickets
        /// O usuário terá o controle dos veículos que ocupam as vagas do estacionamento nesta página.
        /// </summary>
        /// <returns></returns>
        //[Authorize]
        public async Task<ActionResult> Abertos()
        {
            IEnumerable<Ticket> ticket = null;

            using (var httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(urlApi + "ObterTodosNaoPagos");

                var resposta = await httpClient.GetAsync("");
                if (resposta.IsSuccessStatusCode)
                {
                    var lerTask = resposta.Content.ReadAsAsync<IList<Ticket>>();
                    lerTask.Wait();
                    ticket = lerTask.Result;
                }
                else
                {
                    ticket = Enumerable.Empty<Ticket>();
                    ModelState.AddModelError(string.Empty, "Erro no servidor.");
                }
                return View(ticket);
            }
        }
        /// <summary>
        /// Pagina de Entrada
        /// O usuário fará a entrada dos veículos nesta página.
        /// </summary>
        /// <returns></returns>
        //[Authorize]
        public ActionResult Entrada()
        {
            Ticket ticket = new Ticket();
            var data = DateTime.Now;
            ticket.Entrada = data;

            return View(ticket);
        }

        /// <summary>
        /// Botão de Check-In
        /// </summary>
        /// <param name="ticket"></param>
        /// <returns></returns>
        //[Authorize]
        public async Task<ActionResult> BtnCheckIn(Ticket ticket)
        {
            try
            {
                if (ticket == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                using (var httpClient = new HttpClient())
                {
                    ticket.Pago = false;
                    httpClient.BaseAddress = new Uri(urlApi + "Incluir");
                    var resposta = await httpClient.PostAsJsonAsync<Ticket>("", ticket);
                    if (resposta.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Abertos");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Erro no Servidor.");
                    }
                }
                return RedirectToAction("Abertos");
            }
            catch
            {
                return View();
            }
        }

        /// <summary>
        /// Pagina de Saída
        /// O usuário fará a saída dos veículos nesta página.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        //[Authorize]
        public async Task<ActionResult> Saida(int? id)
        {
            if (id == null)
            {
                var service = new TicketService();
                // Busca a lista de produtos e tickets na api
                List<Ticket> tickets = await service.ListarTickets(urlApi + "ObterTodosNaoPagos");

                // Passa para a View um SelectListItem com a lista de tickets
                ViewBag.Tickets = service.SelectListTicket(tickets);

                Ticket ticketS = new Ticket();
                ticketS.Saida = DateTime.Now;
                return View(ticketS);
            }
            
            Ticket ticket = new Ticket();
            ticket.Pago = false;
            using (var httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(urlApi + "ObterId/" + id);

                var resposta = await httpClient.GetAsync("");
                if (resposta.IsSuccessStatusCode)
                {
                    var response = await resposta.Content.ReadAsStringAsync();
                    ticket = JsonConvert.DeserializeObject<Ticket>(response);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Erro no servidor.");
                }

                // FATORAR
                // kkkkkkkkkkkk diferencia dos tempos. ticket.Tempo = ticket.Saida - ticket.Entrada
                ticket.Saida = DateTime.Now;
                var diferencaTempo = ticket.Saida - ticket.Entrada;
                var tempo = diferencaTempo.ToString();
                ticket.Tempo = DateTime.Parse(tempo);

                // FATORAR
                ticket.Valor = 2.50m;
                var horas = ticket.Tempo.Hour + 1;
                var minutos = ticket.Tempo.Minute;
                ticket.ValorTotal = ticket.Valor * horas;

                return View(ticket);
            }
        }

        /// <summary>
        /// Botão Check-Out
        /// </summary>
        /// <param name="ticket"></param>
        /// <returns></returns>
        //[Authorize]
        public async Task<ActionResult> BtnCheckOut(Ticket ticket)
        {
            try
            {
                if (ticket == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                using (var httpClient = new HttpClient())
                {
                    ticket.Pago = false;
                    
                    httpClient.BaseAddress = new Uri(urlApi + "Alterar/" + ticket.Id);

                    var resposta = await httpClient.PutAsJsonAsync("", ticket);
                    if (resposta.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Pagamento", ticket);
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Erro no Servidor.");
                    }
                }
                return RedirectToAction("Abertos");
            }
            catch
            {
                return View();
            }
        }


        /// <summary>
        /// Página de Pagamento, onde o usuário concluirá o pagamento das vagas
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        //[Authorize]
        public async Task<ActionResult> Pagamento(int? id)
        {
            if(id == null)
            {
                var service = new TicketService();
                // Busca a lista de produtos e clientes na api
                List<Ticket> tickets = await service.ListarTickets(urlApi);
                
                // Passa para a View um SelectListItem com a lista de produtos e clientes
                ViewBag.Tickets = service.SelectListTicket(tickets);

                return View();
            }

            Ticket ticket = new Ticket();
            ticket.Pago = false;
            using (var httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(urlApi + "ObterId/" + id);

                var resposta = await httpClient.GetAsync("");
                if (resposta.IsSuccessStatusCode)
                {
                    var response = await resposta.Content.ReadAsStringAsync();
                    ticket = JsonConvert.DeserializeObject<Ticket>(response);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Erro no servidor.");
                }
                return View(ticket);
            }
        }


        /// <summary>
        /// Botão Salvar Pagamento
        /// </summary>
        /// <param name="ticket"></param>
        /// <returns></returns>
        //[Authorize]
        public async Task<ActionResult> SalvarPagamento(Ticket ticket)
        {
            try
            {
                if (ticket == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                // Altera o campo pago da tabela ticket para true
                using (var httpClient = new HttpClient())
                {
                    ticket.Pago = true;
                    httpClient.BaseAddress = new Uri(urlApi + "Alterar/" + ticket.Id);
                    var resposta = await httpClient.PutAsJsonAsync("", ticket);
                    if (!resposta.IsSuccessStatusCode)
                        ModelState.AddModelError(string.Empty, "Erro no Servidor.");
                }

                if(ticket.FormaPagamento.Equals("PIX"))
                    CriarCobranca(ticket.ValorTotal, ticket.Cliente, ticket.Id.ToString());

                // Insere na tabela pagamento
                using (var httpClient = new HttpClient())
                {
                    Pagamento pagamento = new();
                    pagamento.IdTicket = ticket.Id;
                    pagamento.FormaDePagamento = ticket.FormaPagamento;
                    pagamento.ValorTotal = ticket.ValorTotal;
                    pagamento.Desconto = ticket.Desconto;
                    pagamento.ChavePix = ticket.ChavePix;                    
                    

App Estacionamento/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Estacionamento Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/App_Estacionamento.styles.css" asp-append-version="true" />
    <link rel="shortcut icon" href="~/img/favicon.ico" />
    <link href="//cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3 bg-primary">
            <div class="container">
                <a class="navbar-brand font-weight-bold" asp-area="" asp-controller="Home" asp-action="Index">Estacionamento</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-center">

                         <li class="nav-item">
                            <a class="nav-link text-light font-weight-bold" asp-area="" asp-controller="Cliente" asp-action="ListarClientes">Clientes</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light font-weight-bold" asp-area="" asp-controller="Ticket" asp-action="Abertos">Abertos</a>
                        </li>       
                        
                         <li class="nav-item">
                            <a class="nav-link text-light font-weight-bold" asp-area="" asp-controller="Ticket" asp-action="Entrada">Entrada</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-light font-weight-bold" asp-area="" asp-controller="Ticket" asp-action="Saida">Saída</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-light font-weight-bold" asp-area="" asp-controller="Ticket" asp-action="Pagamento">Pagamento</a>
                        </li>       
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>

            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>  
    <script src="~/js/jquery.mask.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.js"></script>
    <script src="~/js/jquery.maskMoney.min.js" type="text/javascript"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>